---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/HelloWorld"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: "nuget"
    directory: "/HelloWorld.xTest"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    
