name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
    - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERSION: 5.0.x

jobs:
#   check_formatting:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: ${{ env.DOTNET_VERSION }}
#     - name: dotnet tools restore
#       run: dotnet tool restore
#     - name: dotnet format check
#       run: dotnet tool run dotnet-format --check

  build_and_test:
    runs-on: ubuntu-latest
    name: build_and_test
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal /p:CollectCoverage=true
